### PR TITLE
Update Makefile and deps (kubebuilder v3.7.0)

### PR DESCRIPTION
**Pull request by weisdd**
The older version of Makefile failed to install some dependencies (e.g. relied on a version of kustomize incompatible with M1) and to pass kubebuilder assets for envtest (used in suite_test.go). To fix that, I used outputs of `kubebuilder init --domain my.domain --repo my.domain/guestbook --plugins=go/v4-alpha` to make some of the changes listed below:

Suggested changes:

- Update Makefile:
  - Fix dependency installation;
  - Bump versions of controller-gen (`v0.7.0` -> `v0.10.0`), kustomize (`v3.8.7` -> `v4.5.7`), and kubebuilder assets (`1.22` -> `1.25.0`);
  - NOTE: the versions are slightly newer than suggested by kubebuilder to reflect the latest features and fixes;
- Generate CRDs with the new controller-gen;
- Update config/manager/kustomization.yaml (format changed a bit, was adjusted automatically by kustomize itself);
- Update Dockerfile to simplify multi-arch image builds;
- Update all direct dependenices except for `grafana-api-golang-client`, because we use a fork.

What wasn't done:

- There are many changes suggested for manifests, didn't copy those. We should consider making them in another PR.

### CODE REVIEW

**Comment by weisdd** [comment]
(resolved conflicts after another PR got merged)

**Comment by pb82** [comment]
thanks! I was having issues with the latest version of kubebuilder and the flags we use `crd:maxDescLen=0,generateEmbeddedObjectMeta=false`. I'll give this a try.

**Comment by weisdd** [comment]
@pb82 I left those flags in place, works just fine. :)
P.S. Since the Makefile commands don't check which versions of the tools are installed, you'll have to clean them up yourself.

**Comment by pb82** [comment]
it all seems to be working fine, thanks

**Review by pb82 — APPROVED** [review]

**Pull request merged**
